apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  namespace: roboshop
  annotations:
    description: "this is catalogue Pod"
    Owner: "niteesh"
    Version: "1.0.0"
spec:
  containers:
    - name: catalogue
      image: niteeshgandham/catalogue:1.0.0
      ports:
        - containerPort: 8080
      env:
        - name: APP_ENV
          value: dev

  