apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    app: nginx
    env: dev
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80

      env:
        - name: APP_ENV
          value: dev