apiVersion: v1
kind: Pod

metadata:
  name: frontend
  namespace: roboshop

spec:
  containers:
    - name: frontend
      image: niteeshgandham/frontend:1.0.0

      ports:
        - containerPort: 80

      env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: APP_NAME

        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: APP_ENV